{"name": "test_4", "status": "skipped", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@pytest.mark.xfail(1 < 2, reason='111')\n    def test_4():\n>       assert 1 == 2\nE       assert 1 == 2\n\ntestcases/auto_test.py:28: AssertionError"}, "start": 1595576803070, "stop": 1595576803070, "uuid": "82b4a19f-a232-4a14-aa8f-d6e2c543e89b", "historyId": "46ac074fd109df8fa658b147e10d1542", "testCaseId": "1359d36d63ce7b8a1a2025eb0eaaef38", "fullName": "testcases.auto_test#test_4", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(True, reason='111')"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "auto_test"}, {"name": "host", "value": "duan-XPS-15-9570"}, {"name": "thread", "value": "12965-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.auto_test"}]}